
PACKAGE curl

LIBRARY libcurl.so

PRIVATE


PUBLIC

FUNCTION: curl_global_init ( i -- e )
FUNCTION: curl_easy_init ( -- h )
FUNCTION: curl_easy_setopt ( h i *a -- e )
FUNCTION: curl_easy_perform ( h -- e )
FUNCTION: curl_easy_getinfo ( h i ? -- e )
FUNCTION: curl_easy_reset ( h -- )
FUNCTION: curl_easy_cleanup ( h -- )
FUNCTION: curl_easy_escape ( h s n -- a )
FUNCTION: curl_easy_unescape ( h s n *i -- a )
FUNCTION: curl_easy_duphandle ( h1 -- h2 )
\ FUNCTION: curl_easy_header ( h s i i i *a -- e )
\ FUNCTION: curl_easy_nextheader ( h i i *p -- a )
FUNCTION: curl_easy_pause ( h i -- e )
FUNCTION: curl_easy_upkeep ( h -- e )
FUNCTION: curl_easy_recv ( h a n *n -- e )
FUNCTION: curl_easy_send ( h a n *n -- e )
FUNCTION: curl_easy_option_by_id ( i -- a )
FUNCTION: curl_easy_option_by_name ( s -- a )
FUNCTION: curl_easy_option_next ( p -- a )
FUNCTION: curl_easy_strerror ( e -- s )
\ FUNCTION: curl_easy_ssls_export ( h cb p -- e )
\ FUNCTION: curl_easy_ssls_import ( h s a1 n1 a2 n2 -- e )

: CURLOPT header postpone (constant) + , ;   \ # type CURLOPT

1 CONSTANT CURL_GLOBAL_ALL	\ 3 if WIN32
0 CONSTANT CURLE_OK

    0 CONSTANT CURLOPTTYPE_LONG
10000 CONSTANT CURLOPTTYPE_OBJECTPOINT   
20000 CONSTANT CURLOPTTYPE_FUNCTIONPOINT 
30000 CONSTANT CURLOPTTYPE_OFF_T         
40000 CONSTANT CURLOPTTYPE_BLOB          

CURLOPTTYPE_OBJECTPOINT CONSTANT CURLOPTTYPE_STRINGPOINT
CURLOPTTYPE_OBJECTPOINT CONSTANT CURLOPTTYPE_SLISTPOINT
CURLOPTTYPE_OBJECTPOINT CONSTANT CURLOPTTYPE_CBPOINT
CURLOPTTYPE_LONG CONSTANT CURLOPTTYPE_VALUES

 1 	 CURLOPTTYPE_CBPOINT		CURLOPT	CURLOPT_WRITEDATA
 2 	 CURLOPTTYPE_STRINGPOINT	CURLOPT	CURLOPT_URL
 3 	 CURLOPTTYPE_LONG		CURLOPT	CURLOPT_PORT
 4 	 CURLOPTTYPE_STRINGPOINT	CURLOPT	CURLOPT_PROXY
 5 	 CURLOPTTYPE_STRINGPOINT	CURLOPT	CURLOPT_USERPWD
 6 	 CURLOPTTYPE_STRINGPOINT	CURLOPT	CURLOPT_PROXYUSERPWD
 7 	 CURLOPTTYPE_STRINGPOINT	CURLOPT	CURLOPT_RANGE
 9 	 CURLOPTTYPE_CBPOINT		CURLOPT	CURLOPT_READDATA
 10 	 CURLOPTTYPE_OBJECTPOINT	CURLOPT	CURLOPT_ERRORBUFFER
 11 	 CURLOPTTYPE_FUNCTIONPOINT	CURLOPT	CURLOPT_WRITEFUNCTION
 12 	 CURLOPTTYPE_FUNCTIONPOINT	CURLOPT	CURLOPT_READFUNCTION
 13 	 CURLOPTTYPE_LONG		CURLOPT	CURLOPT_TIMEOUT
 14 	 CURLOPTTYPE_LONG		CURLOPT	CURLOPT_INFILESIZE
 15 	 CURLOPTTYPE_OBJECTPOINT	CURLOPT	CURLOPT_POSTFIELDS
 16 	 CURLOPTTYPE_STRINGPOINT	CURLOPT	CURLOPT_REFERER
 17 	 CURLOPTTYPE_STRINGPOINT	CURLOPT	CURLOPT_FTPPORT
 18 	 CURLOPTTYPE_STRINGPOINT	CURLOPT	CURLOPT_USERAGENT
 19 	 CURLOPTTYPE_LONG		CURLOPT	CURLOPT_LOW_SPEED_LIMIT
 20 	 CURLOPTTYPE_LONG		CURLOPT	CURLOPT_LOW_SPEED_TIME
 21 	 CURLOPTTYPE_LONG		CURLOPT	CURLOPT_RESUME_FROM
 22 	 CURLOPTTYPE_STRINGPOINT	CURLOPT	CURLOPT_COOKIE
 23 	 CURLOPTTYPE_SLISTPOINT		CURLOPT	CURLOPT_HTTPHEADER
 25 	 CURLOPTTYPE_STRINGPOINT	CURLOPT	CURLOPT_SSLCERT
 26 	 CURLOPTTYPE_STRINGPOINT	CURLOPT	CURLOPT_KEYPASSWD
 27 	 CURLOPTTYPE_LONG		CURLOPT	CURLOPT_CRLF
 28 	 CURLOPTTYPE_SLISTPOINT		CURLOPT	CURLOPT_QUOTE
 29 	 CURLOPTTYPE_CBPOINT		CURLOPT	CURLOPT_HEADERDATA
 31 	 CURLOPTTYPE_STRINGPOINT	CURLOPT	CURLOPT_COOKIEFILE
 32 	 CURLOPTTYPE_VALUES		CURLOPT	CURLOPT_SSLVERSION
 33 	 CURLOPTTYPE_VALUES		CURLOPT	CURLOPT_TIMECONDITION
 34 	 CURLOPTTYPE_LONG		CURLOPT	CURLOPT_TIMEVALUE
 36 	 CURLOPTTYPE_STRINGPOINT	CURLOPT	CURLOPT_CUSTOMREQUEST
 37 	 CURLOPTTYPE_OBJECTPOINT	CURLOPT	CURLOPT_STDERR
 39 	 CURLOPTTYPE_SLISTPOINT		CURLOPT	CURLOPT_POSTQUOTE
 40 	 CURLOPTTYPE_OBJECTPOINT	CURLOPT	CURLOPT_OBSOLETE40
 41 	 CURLOPTTYPE_LONG		CURLOPT	CURLOPT_VERBOSE
 42 	 CURLOPTTYPE_LONG		CURLOPT	CURLOPT_HEADER
 43 	 CURLOPTTYPE_LONG		CURLOPT	CURLOPT_NOPROGRESS
 44 	 CURLOPTTYPE_LONG		CURLOPT	CURLOPT_NOBODY
 45 	 CURLOPTTYPE_LONG		CURLOPT	CURLOPT_FAILONERROR
 46 	 CURLOPTTYPE_LONG		CURLOPT	CURLOPT_UPLOAD
 47 	 CURLOPTTYPE_LONG		CURLOPT	CURLOPT_POST
 48 	 CURLOPTTYPE_LONG		CURLOPT	CURLOPT_DIRLISTONLY
 50 	 CURLOPTTYPE_LONG		CURLOPT	CURLOPT_APPEND
 51 	 CURLOPTTYPE_VALUES		CURLOPT	CURLOPT_NETRC
 52 	 CURLOPTTYPE_LONG		CURLOPT	CURLOPT_FOLLOWLOCATION
 53 	 CURLOPTTYPE_LONG		CURLOPT	CURLOPT_TRANSFERTEXT
 57 	 CURLOPTTYPE_CBPOINT		CURLOPT	CURLOPT_XFERINFODATA
 57 	 CURLOPTTYPE_CBPOINT		CURLOPT	CURLOPT_PROGRESSDATA
 58 	 CURLOPTTYPE_LONG		CURLOPT	CURLOPT_AUTOREFERER
 59 	 CURLOPTTYPE_LONG		CURLOPT	CURLOPT_PROXYPORT
 60 	 CURLOPTTYPE_LONG		CURLOPT	CURLOPT_POSTFIELDSIZE
 61 	 CURLOPTTYPE_LONG		CURLOPT	CURLOPT_HTTPPROXYTUNNEL
 62 	 CURLOPTTYPE_STRINGPOINT	CURLOPT	CURLOPT_INTERFACE
 63 	 CURLOPTTYPE_STRINGPOINT	CURLOPT	CURLOPT_KRBLEVEL
 64 	 CURLOPTTYPE_LONG		CURLOPT	CURLOPT_SSL_VERIFYPEER
 65 	 CURLOPTTYPE_STRINGPOINT	CURLOPT	CURLOPT_CAINFO
 68 	 CURLOPTTYPE_LONG		CURLOPT	CURLOPT_MAXREDIRS
 69 	 CURLOPTTYPE_LONG		CURLOPT	CURLOPT_FILETIME
 70 	 CURLOPTTYPE_SLISTPOINT		CURLOPT	CURLOPT_TELNETOPTIONS
 71 	 CURLOPTTYPE_LONG		CURLOPT	CURLOPT_MAXCONNECTS
 72 	 CURLOPTTYPE_LONG		CURLOPT	CURLOPT_OBSOLETE72
 74 	 CURLOPTTYPE_LONG		CURLOPT	CURLOPT_FRESH_CONNECT
 75 	 CURLOPTTYPE_LONG		CURLOPT	CURLOPT_FORBID_REUSE
 78 	 CURLOPTTYPE_LONG		CURLOPT	CURLOPT_CONNECTTIMEOUT
 79 	 CURLOPTTYPE_FUNCTIONPOINT	CURLOPT	CURLOPT_HEADERFUNCTION
 80 	 CURLOPTTYPE_LONG		CURLOPT	CURLOPT_HTTPGET
 81 	 CURLOPTTYPE_LONG		CURLOPT	CURLOPT_SSL_VERIFYHOST
 82 	 CURLOPTTYPE_STRINGPOINT	CURLOPT	CURLOPT_COOKIEJAR
 83 	 CURLOPTTYPE_STRINGPOINT	CURLOPT	CURLOPT_SSL_CIPHER_LIST
 84 	 CURLOPTTYPE_VALUES		CURLOPT	CURLOPT_HTTP_VERSION
 85 	 CURLOPTTYPE_LONG		CURLOPT	CURLOPT_FTP_USE_EPSV
 86 	 CURLOPTTYPE_STRINGPOINT	CURLOPT	CURLOPT_SSLCERTTYPE
 87 	 CURLOPTTYPE_STRINGPOINT	CURLOPT	CURLOPT_SSLKEY
 88 	 CURLOPTTYPE_STRINGPOINT	CURLOPT	CURLOPT_SSLKEYTYPE
 89 	 CURLOPTTYPE_STRINGPOINT	CURLOPT	CURLOPT_SSLENGINE
 90 	 CURLOPTTYPE_LONG		CURLOPT	CURLOPT_SSLENGINE_DEFAULT
 92 	 CURLOPTTYPE_LONG		CURLOPT	CURLOPT_DNS_CACHE_TIMEOUT
 93 	 CURLOPTTYPE_SLISTPOINT		CURLOPT	CURLOPT_PREQUOTE
 94 	 CURLOPTTYPE_FUNCTIONPOINT	CURLOPT	CURLOPT_DEBUGFUNCTION
 95 	 CURLOPTTYPE_CBPOINT		CURLOPT	CURLOPT_DEBUGDATA
 96 	 CURLOPTTYPE_LONG		CURLOPT	CURLOPT_COOKIESESSION
 97 	 CURLOPTTYPE_STRINGPOINT	CURLOPT	CURLOPT_CAPATH
 98 	 CURLOPTTYPE_LONG		CURLOPT	CURLOPT_BUFFERSIZE
 99 	 CURLOPTTYPE_LONG		CURLOPT	CURLOPT_NOSIGNAL
 100 	 CURLOPTTYPE_OBJECTPOINT	CURLOPT	CURLOPT_SHARE
 101 	 CURLOPTTYPE_VALUES		CURLOPT	CURLOPT_PROXYTYPE
 102 	 CURLOPTTYPE_STRINGPOINT	CURLOPT	CURLOPT_ACCEPT_ENCODING
 103 	 CURLOPTTYPE_OBJECTPOINT	CURLOPT	CURLOPT_PRIVATE
 104 	 CURLOPTTYPE_SLISTPOINT		CURLOPT	CURLOPT_HTTP200ALIASES
 105 	 CURLOPTTYPE_LONG		CURLOPT	CURLOPT_UNRESTRICTED_AUTH
 106 	 CURLOPTTYPE_LONG		CURLOPT	CURLOPT_FTP_USE_EPRT
 107 	 CURLOPTTYPE_VALUES		CURLOPT	CURLOPT_HTTPAUTH
 108 	 CURLOPTTYPE_FUNCTIONPOINT	CURLOPT	CURLOPT_SSL_CTX_FUNCTION
 109 	 CURLOPTTYPE_CBPOINT		CURLOPT	CURLOPT_SSL_CTX_DATA
 110 	 CURLOPTTYPE_LONG		CURLOPT	CURLOPT_FTP_CREATE_MISSING_DIRS
 111 	 CURLOPTTYPE_VALUES		CURLOPT	CURLOPT_PROXYAUTH
 112 	 CURLOPTTYPE_LONG		CURLOPT	CURLOPT_SERVER_RESPONSE_TIMEOUT
 113 	 CURLOPTTYPE_VALUES		CURLOPT	CURLOPT_IPRESOLVE
 114 	 CURLOPTTYPE_LONG		CURLOPT	CURLOPT_MAXFILESIZE
 115 	 CURLOPTTYPE_OFF_T		CURLOPT	CURLOPT_INFILESIZE_LARGE
 116 	 CURLOPTTYPE_OFF_T		CURLOPT	CURLOPT_RESUME_FROM_LARGE
 117 	 CURLOPTTYPE_OFF_T		CURLOPT	CURLOPT_MAXFILESIZE_LARGE
 118 	 CURLOPTTYPE_STRINGPOINT	CURLOPT	CURLOPT_NETRC_FILE
 119 	 CURLOPTTYPE_VALUES		CURLOPT	CURLOPT_USE_SSL
 120 	 CURLOPTTYPE_OFF_T		CURLOPT	CURLOPT_POSTFIELDSIZE_LARGE
 121 	 CURLOPTTYPE_LONG		CURLOPT	CURLOPT_TCP_NODELAY
 129 	 CURLOPTTYPE_VALUES		CURLOPT	CURLOPT_FTPSSLAUTH
 134 	 CURLOPTTYPE_STRINGPOINT	CURLOPT	CURLOPT_FTP_ACCOUNT
 135 	 CURLOPTTYPE_STRINGPOINT	CURLOPT	CURLOPT_COOKIELIST
 136 	 CURLOPTTYPE_LONG		CURLOPT	CURLOPT_IGNORE_CONTENT_LENGTH
 137 	 CURLOPTTYPE_LONG		CURLOPT	CURLOPT_FTP_SKIP_PASV_IP
 138 	 CURLOPTTYPE_VALUES		CURLOPT	CURLOPT_FTP_FILEMETHOD
 139 	 CURLOPTTYPE_LONG		CURLOPT	CURLOPT_LOCALPORT
 140 	 CURLOPTTYPE_LONG		CURLOPT	CURLOPT_LOCALPORTRANGE
 141 	 CURLOPTTYPE_LONG		CURLOPT	CURLOPT_CONNECT_ONLY
 145 	 CURLOPTTYPE_OFF_T		CURLOPT	CURLOPT_MAX_SEND_SPEED_LARGE
 146 	 CURLOPTTYPE_OFF_T		CURLOPT	CURLOPT_MAX_RECV_SPEED_LARGE
 147 	 CURLOPTTYPE_STRINGPOINT	CURLOPT	CURLOPT_FTP_ALTERNATIVE_TO_USER
 148 	 CURLOPTTYPE_FUNCTIONPOINT	CURLOPT	CURLOPT_SOCKOPTFUNCTION
 149 	 CURLOPTTYPE_CBPOINT		CURLOPT	CURLOPT_SOCKOPTDATA
 150 	 CURLOPTTYPE_LONG		CURLOPT	CURLOPT_SSL_SESSIONID_CACHE
 151 	 CURLOPTTYPE_VALUES		CURLOPT	CURLOPT_SSH_AUTH_TYPES
 152 	 CURLOPTTYPE_STRINGPOINT	CURLOPT	CURLOPT_SSH_PUBLIC_KEYFILE
 153 	 CURLOPTTYPE_STRINGPOINT	CURLOPT	CURLOPT_SSH_PRIVATE_KEYFILE
 154 	 CURLOPTTYPE_LONG		CURLOPT	CURLOPT_FTP_SSL_CCC
 155 	 CURLOPTTYPE_LONG		CURLOPT	CURLOPT_TIMEOUT_MS
 156 	 CURLOPTTYPE_LONG		CURLOPT	CURLOPT_CONNECTTIMEOUT_MS
 157 	 CURLOPTTYPE_LONG		CURLOPT	CURLOPT_HTTP_TRANSFER_DECODING
 158 	 CURLOPTTYPE_LONG		CURLOPT	CURLOPT_HTTP_CONTENT_DECODING
 159 	 CURLOPTTYPE_LONG		CURLOPT	CURLOPT_NEW_FILE_PERMS
 160 	 CURLOPTTYPE_LONG		CURLOPT	CURLOPT_NEW_DIRECTORY_PERMS
 161 	 CURLOPTTYPE_VALUES		CURLOPT	CURLOPT_POSTREDIR
 162 	 CURLOPTTYPE_STRINGPOINT	CURLOPT	CURLOPT_SSH_HOST_PUBLIC_KEY_MD5
 163 	 CURLOPTTYPE_FUNCTIONPOINT	CURLOPT	CURLOPT_OPENSOCKETFUNCTION
 164 	 CURLOPTTYPE_CBPOINT		CURLOPT	CURLOPT_OPENSOCKETDATA
 165 	 CURLOPTTYPE_OBJECTPOINT	CURLOPT	CURLOPT_COPYPOSTFIELDS
 166 	 CURLOPTTYPE_LONG		CURLOPT	CURLOPT_PROXY_TRANSFER_MODE
 167 	 CURLOPTTYPE_FUNCTIONPOINT	CURLOPT	CURLOPT_SEEKFUNCTION
 168 	 CURLOPTTYPE_CBPOINT		CURLOPT	CURLOPT_SEEKDATA
 169 	 CURLOPTTYPE_STRINGPOINT	CURLOPT	CURLOPT_CRLFILE
 170 	 CURLOPTTYPE_STRINGPOINT	CURLOPT	CURLOPT_ISSUERCERT
 171 	 CURLOPTTYPE_LONG		CURLOPT	CURLOPT_ADDRESS_SCOPE
 172 	 CURLOPTTYPE_LONG		CURLOPT	CURLOPT_CERTINFO
 173 	 CURLOPTTYPE_STRINGPOINT	CURLOPT	CURLOPT_USERNAME
 174 	 CURLOPTTYPE_STRINGPOINT	CURLOPT	CURLOPT_PASSWORD
 175 	 CURLOPTTYPE_STRINGPOINT	CURLOPT	CURLOPT_PROXYUSERNAME
 176 	 CURLOPTTYPE_STRINGPOINT	CURLOPT	CURLOPT_PROXYPASSWORD
 177 	 CURLOPTTYPE_STRINGPOINT	CURLOPT	CURLOPT_NOPROXY
 178 	 CURLOPTTYPE_LONG		CURLOPT	CURLOPT_TFTP_BLKSIZE
 180 	 CURLOPTTYPE_LONG		CURLOPT	CURLOPT_SOCKS5_GSSAPI_NEC
 183 	 CURLOPTTYPE_STRINGPOINT	CURLOPT	CURLOPT_SSH_KNOWNHOSTS
 184 	 CURLOPTTYPE_FUNCTIONPOINT	CURLOPT	CURLOPT_SSH_KEYFUNCTION
 185 	 CURLOPTTYPE_CBPOINT		CURLOPT	CURLOPT_SSH_KEYDATA
 186 	 CURLOPTTYPE_STRINGPOINT	CURLOPT	CURLOPT_MAIL_FROM
 187 	 CURLOPTTYPE_SLISTPOINT		CURLOPT	CURLOPT_MAIL_RCPT
 188 	 CURLOPTTYPE_LONG		CURLOPT	CURLOPT_FTP_USE_PRET
 189 	 CURLOPTTYPE_VALUES		CURLOPT	CURLOPT_RTSP_REQUEST
 190 	 CURLOPTTYPE_STRINGPOINT	CURLOPT	CURLOPT_RTSP_SESSION_ID
 191 	 CURLOPTTYPE_STRINGPOINT	CURLOPT	CURLOPT_RTSP_STREAM_URI
 192 	 CURLOPTTYPE_STRINGPOINT	CURLOPT	CURLOPT_RTSP_TRANSPORT
 193 	 CURLOPTTYPE_LONG		CURLOPT	CURLOPT_RTSP_CLIENT_CSEQ
 194 	 CURLOPTTYPE_LONG		CURLOPT	CURLOPT_RTSP_SERVER_CSEQ
 195 	 CURLOPTTYPE_CBPOINT		CURLOPT	CURLOPT_INTERLEAVEDATA
 196 	 CURLOPTTYPE_FUNCTIONPOINT	CURLOPT	CURLOPT_INTERLEAVEFUNCTION
 197 	 CURLOPTTYPE_LONG		CURLOPT	CURLOPT_WILDCARDMATCH
 198 	 CURLOPTTYPE_FUNCTIONPOINT	CURLOPT	CURLOPT_CHUNK_BGN_FUNCTION
 199 	 CURLOPTTYPE_FUNCTIONPOINT	CURLOPT	CURLOPT_CHUNK_END_FUNCTION
 200 	 CURLOPTTYPE_FUNCTIONPOINT	CURLOPT	CURLOPT_FNMATCH_FUNCTION
 201 	 CURLOPTTYPE_CBPOINT		CURLOPT	CURLOPT_CHUNK_DATA
 202 	 CURLOPTTYPE_CBPOINT		CURLOPT	CURLOPT_FNMATCH_DATA
 203 	 CURLOPTTYPE_SLISTPOINT		CURLOPT	CURLOPT_RESOLVE
 204 	 CURLOPTTYPE_STRINGPOINT	CURLOPT	CURLOPT_TLSAUTH_USERNAME
 205 	 CURLOPTTYPE_STRINGPOINT	CURLOPT	CURLOPT_TLSAUTH_PASSWORD
 206 	 CURLOPTTYPE_STRINGPOINT	CURLOPT	CURLOPT_TLSAUTH_TYPE
 207 	 CURLOPTTYPE_LONG		CURLOPT	CURLOPT_TRANSFER_ENCODING
 208 	 CURLOPTTYPE_FUNCTIONPOINT	CURLOPT	CURLOPT_CLOSESOCKETFUNCTION
 209 	 CURLOPTTYPE_CBPOINT		CURLOPT	CURLOPT_CLOSESOCKETDATA
 210 	 CURLOPTTYPE_VALUES		CURLOPT	CURLOPT_GSSAPI_DELEGATION
 211 	 CURLOPTTYPE_STRINGPOINT	CURLOPT	CURLOPT_DNS_SERVERS
 212 	 CURLOPTTYPE_LONG		CURLOPT	CURLOPT_ACCEPTTIMEOUT_MS
 213 	 CURLOPTTYPE_LONG		CURLOPT	CURLOPT_TCP_KEEPALIVE
 214 	 CURLOPTTYPE_LONG		CURLOPT	CURLOPT_TCP_KEEPIDLE
 215 	 CURLOPTTYPE_LONG		CURLOPT	CURLOPT_TCP_KEEPINTVL
 216 	 CURLOPTTYPE_VALUES		CURLOPT	CURLOPT_SSL_OPTIONS
 217 	 CURLOPTTYPE_STRINGPOINT	CURLOPT	CURLOPT_MAIL_AUTH
 218 	 CURLOPTTYPE_LONG		CURLOPT	CURLOPT_SASL_IR
 219 	 CURLOPTTYPE_FUNCTIONPOINT	CURLOPT	CURLOPT_XFERINFOFUNCTION
 220 	 CURLOPTTYPE_STRINGPOINT	CURLOPT	CURLOPT_XOAUTH2_BEARER
 221 	 CURLOPTTYPE_STRINGPOINT	CURLOPT	CURLOPT_DNS_INTERFACE
 222 	 CURLOPTTYPE_STRINGPOINT	CURLOPT	CURLOPT_DNS_LOCAL_IP4
 223 	 CURLOPTTYPE_STRINGPOINT	CURLOPT	CURLOPT_DNS_LOCAL_IP6
 224 	 CURLOPTTYPE_STRINGPOINT	CURLOPT	CURLOPT_LOGIN_OPTIONS
 226 	 CURLOPTTYPE_LONG		CURLOPT	CURLOPT_SSL_ENABLE_ALPN
 227 	 CURLOPTTYPE_LONG		CURLOPT	CURLOPT_EXPECT_100_TIMEOUT_MS
 228 	 CURLOPTTYPE_SLISTPOINT		CURLOPT	CURLOPT_PROXYHEADER
 229 	 CURLOPTTYPE_VALUES		CURLOPT	CURLOPT_HEADEROPT
 230 	 CURLOPTTYPE_STRINGPOINT	CURLOPT	CURLOPT_PINNEDPUBLICKEY
 231 	 CURLOPTTYPE_STRINGPOINT	CURLOPT	CURLOPT_UNIX_SOCKET_PATH
 232 	 CURLOPTTYPE_LONG		CURLOPT	CURLOPT_SSL_VERIFYSTATUS
 233 	 CURLOPTTYPE_LONG		CURLOPT	CURLOPT_SSL_FALSESTART
 234 	 CURLOPTTYPE_LONG		CURLOPT	CURLOPT_PATH_AS_IS
 235 	 CURLOPTTYPE_STRINGPOINT	CURLOPT	CURLOPT_PROXY_SERVICE_NAME
 236 	 CURLOPTTYPE_STRINGPOINT	CURLOPT	CURLOPT_SERVICE_NAME
 237 	 CURLOPTTYPE_LONG		CURLOPT	CURLOPT_PIPEWAIT
 238 	 CURLOPTTYPE_STRINGPOINT	CURLOPT	CURLOPT_DEFAULT_PROTOCOL
 239 	 CURLOPTTYPE_LONG		CURLOPT	CURLOPT_STREAM_WEIGHT
 240 	 CURLOPTTYPE_OBJECTPOINT	CURLOPT	CURLOPT_STREAM_DEPENDS
 241 	 CURLOPTTYPE_OBJECTPOINT	CURLOPT	CURLOPT_STREAM_DEPENDS_E
 242 	 CURLOPTTYPE_LONG		CURLOPT	CURLOPT_TFTP_NO_OPTIONS
 243 	 CURLOPTTYPE_SLISTPOINT		CURLOPT	CURLOPT_CONNECT_TO
 244 	 CURLOPTTYPE_LONG		CURLOPT	CURLOPT_TCP_FASTOPEN
 245 	 CURLOPTTYPE_LONG		CURLOPT	CURLOPT_KEEP_SENDING_ON_ERROR
 246 	 CURLOPTTYPE_STRINGPOINT	CURLOPT	CURLOPT_PROXY_CAINFO
 247 	 CURLOPTTYPE_STRINGPOINT	CURLOPT	CURLOPT_PROXY_CAPATH
 248 	 CURLOPTTYPE_LONG		CURLOPT	CURLOPT_PROXY_SSL_VERIFYPEER
 249 	 CURLOPTTYPE_LONG		CURLOPT	CURLOPT_PROXY_SSL_VERIFYHOST
 250 	 CURLOPTTYPE_VALUES		CURLOPT	CURLOPT_PROXY_SSLVERSION
 251 	 CURLOPTTYPE_STRINGPOINT	CURLOPT	CURLOPT_PROXY_TLSAUTH_USERNAME
 252 	 CURLOPTTYPE_STRINGPOINT	CURLOPT	CURLOPT_PROXY_TLSAUTH_PASSWORD
 253 	 CURLOPTTYPE_STRINGPOINT	CURLOPT	CURLOPT_PROXY_TLSAUTH_TYPE
 254 	 CURLOPTTYPE_STRINGPOINT	CURLOPT	CURLOPT_PROXY_SSLCERT
 255 	 CURLOPTTYPE_STRINGPOINT	CURLOPT	CURLOPT_PROXY_SSLCERTTYPE
 256 	 CURLOPTTYPE_STRINGPOINT	CURLOPT	CURLOPT_PROXY_SSLKEY
 257 	 CURLOPTTYPE_STRINGPOINT	CURLOPT	CURLOPT_PROXY_SSLKEYTYPE
 258 	 CURLOPTTYPE_STRINGPOINT	CURLOPT	CURLOPT_PROXY_KEYPASSWD
 259 	 CURLOPTTYPE_STRINGPOINT	CURLOPT	CURLOPT_PROXY_SSL_CIPHER_LIST
 260 	 CURLOPTTYPE_STRINGPOINT	CURLOPT	CURLOPT_PROXY_CRLFILE
 261 	 CURLOPTTYPE_LONG		CURLOPT	CURLOPT_PROXY_SSL_OPTIONS
 262 	 CURLOPTTYPE_STRINGPOINT	CURLOPT	CURLOPT_PRE_PROXY
 263 	 CURLOPTTYPE_STRINGPOINT	CURLOPT	CURLOPT_PROXY_PINNEDPUBLICKEY
 264 	 CURLOPTTYPE_STRINGPOINT	CURLOPT	CURLOPT_ABSTRACT_UNIX_SOCKET
 265 	 CURLOPTTYPE_LONG		CURLOPT	CURLOPT_SUPPRESS_CONNECT_HEADERS
 266 	 CURLOPTTYPE_STRINGPOINT	CURLOPT	CURLOPT_REQUEST_TARGET
 267 	 CURLOPTTYPE_LONG		CURLOPT	CURLOPT_SOCKS5_AUTH
 268 	 CURLOPTTYPE_LONG		CURLOPT	CURLOPT_SSH_COMPRESSION
 269 	 CURLOPTTYPE_OBJECTPOINT	CURLOPT	CURLOPT_MIMEPOST
 270 	 CURLOPTTYPE_OFF_T		CURLOPT	CURLOPT_TIMEVALUE_LARGE
 271 	 CURLOPTTYPE_LONG		CURLOPT	CURLOPT_HAPPY_EYEBALLS_TIMEOUT_MS
 272 	 CURLOPTTYPE_FUNCTIONPOINT	CURLOPT	CURLOPT_RESOLVER_START_FUNCTION
 273 	 CURLOPTTYPE_CBPOINT		CURLOPT	CURLOPT_RESOLVER_START_DATA
 274 	 CURLOPTTYPE_LONG		CURLOPT	CURLOPT_HAPROXYPROTOCOL
 275 	 CURLOPTTYPE_LONG		CURLOPT	CURLOPT_DNS_SHUFFLE_ADDRESSES
 276 	 CURLOPTTYPE_STRINGPOINT	CURLOPT	CURLOPT_TLS13_CIPHERS
 277 	 CURLOPTTYPE_STRINGPOINT	CURLOPT	CURLOPT_PROXY_TLS13_CIPHERS
 278 	 CURLOPTTYPE_LONG		CURLOPT	CURLOPT_DISALLOW_USERNAME_IN_URL
 279 	 CURLOPTTYPE_STRINGPOINT	CURLOPT	CURLOPT_DOH_URL
 280 	 CURLOPTTYPE_LONG		CURLOPT	CURLOPT_UPLOAD_BUFFERSIZE
 281 	 CURLOPTTYPE_LONG		CURLOPT	CURLOPT_UPKEEP_INTERVAL_MS
 282 	 CURLOPTTYPE_OBJECTPOINT	CURLOPT	CURLOPT_CURLU
 283 	 CURLOPTTYPE_FUNCTIONPOINT	CURLOPT	CURLOPT_TRAILERFUNCTION
 284 	 CURLOPTTYPE_CBPOINT		CURLOPT	CURLOPT_TRAILERDATA
 285 	 CURLOPTTYPE_LONG		CURLOPT	CURLOPT_HTTP09_ALLOWED
 286 	 CURLOPTTYPE_LONG		CURLOPT	CURLOPT_ALTSVC_CTRL
 287 	 CURLOPTTYPE_STRINGPOINT	CURLOPT	CURLOPT_ALTSVC
 288 	 CURLOPTTYPE_LONG		CURLOPT	CURLOPT_MAXAGE_CONN
 289 	 CURLOPTTYPE_STRINGPOINT	CURLOPT	CURLOPT_SASL_AUTHZID
 290 	 CURLOPTTYPE_LONG		CURLOPT	CURLOPT_MAIL_RCPT_ALLOWFAILS
 291 	 CURLOPTTYPE_BLOB		CURLOPT	CURLOPT_SSLCERT_BLOB
 292 	 CURLOPTTYPE_BLOB		CURLOPT	CURLOPT_SSLKEY_BLOB
 293 	 CURLOPTTYPE_BLOB		CURLOPT	CURLOPT_PROXY_SSLCERT_BLOB
 294 	 CURLOPTTYPE_BLOB		CURLOPT	CURLOPT_PROXY_SSLKEY_BLOB
 295 	 CURLOPTTYPE_BLOB		CURLOPT	CURLOPT_ISSUERCERT_BLOB
 296 	 CURLOPTTYPE_STRINGPOINT	CURLOPT	CURLOPT_PROXY_ISSUERCERT
 297 	 CURLOPTTYPE_BLOB		CURLOPT	CURLOPT_PROXY_ISSUERCERT_BLOB
 298 	 CURLOPTTYPE_STRINGPOINT	CURLOPT	CURLOPT_SSL_EC_CURVES
 299 	 CURLOPTTYPE_LONG		CURLOPT	CURLOPT_HSTS_CTRL
 300 	 CURLOPTTYPE_STRINGPOINT	CURLOPT	CURLOPT_HSTS
 301 	 CURLOPTTYPE_FUNCTIONPOINT	CURLOPT	CURLOPT_HSTSREADFUNCTION
 302 	 CURLOPTTYPE_CBPOINT		CURLOPT	CURLOPT_HSTSREADDATA
 303 	 CURLOPTTYPE_FUNCTIONPOINT	CURLOPT	CURLOPT_HSTSWRITEFUNCTION
 304 	 CURLOPTTYPE_CBPOINT		CURLOPT	CURLOPT_HSTSWRITEDATA
 305 	 CURLOPTTYPE_STRINGPOINT	CURLOPT	CURLOPT_AWS_SIGV4
 306 	 CURLOPTTYPE_LONG		CURLOPT	CURLOPT_DOH_SSL_VERIFYPEER
 307 	 CURLOPTTYPE_LONG		CURLOPT	CURLOPT_DOH_SSL_VERIFYHOST
 308 	 CURLOPTTYPE_LONG		CURLOPT	CURLOPT_DOH_SSL_VERIFYSTATUS
 309 	 CURLOPTTYPE_BLOB		CURLOPT	CURLOPT_CAINFO_BLOB
 310 	 CURLOPTTYPE_BLOB		CURLOPT	CURLOPT_PROXY_CAINFO_BLOB
 311 	 CURLOPTTYPE_STRINGPOINT	CURLOPT	CURLOPT_SSH_HOST_PUBLIC_KEY_SHA256
 312 	 CURLOPTTYPE_FUNCTIONPOINT	CURLOPT	CURLOPT_PREREQFUNCTION
 313 	 CURLOPTTYPE_CBPOINT		CURLOPT	CURLOPT_PREREQDATA
 314 	 CURLOPTTYPE_LONG		CURLOPT	CURLOPT_MAXLIFETIME_CONN
 315 	 CURLOPTTYPE_LONG		CURLOPT	CURLOPT_MIME_OPTIONS
 316 	 CURLOPTTYPE_FUNCTIONPOINT	CURLOPT	CURLOPT_SSH_HOSTKEYFUNCTION
 317 	 CURLOPTTYPE_CBPOINT		CURLOPT	CURLOPT_SSH_HOSTKEYDATA
 318 	 CURLOPTTYPE_STRINGPOINT	CURLOPT	CURLOPT_PROTOCOLS_STR
 319 	 CURLOPTTYPE_STRINGPOINT	CURLOPT	CURLOPT_REDIR_PROTOCOLS_STR
 320 	 CURLOPTTYPE_LONG		CURLOPT	CURLOPT_WS_OPTIONS
 321 	 CURLOPTTYPE_LONG		CURLOPT	CURLOPT_CA_CACHE_TIMEOUT
 322 	 CURLOPTTYPE_LONG		CURLOPT	CURLOPT_QUICK_EXIT
 323 	 CURLOPTTYPE_STRINGPOINT	CURLOPT	CURLOPT_HAPROXY_CLIENT_IP
 324 	 CURLOPTTYPE_LONG		CURLOPT	CURLOPT_SERVER_RESPONSE_TIMEOUT_MS

END-PACKAGE
